openapi: 3.1.0
info:
  version: 1.0.0
  title: Spendy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my spendy app
tags:
  - name: Auth
    description: Operations related to user interaction with the application
servers:
  - url: https://yourdomain.dev/api
  # - url: https://nodejs-hw-mongodb-0u7h.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'

  # /contacts/{id}:
  #   get:
  #     $ref: '../swagger/paths/contacts/{id}/get.yaml'
  #   patch:
  #     $ref: '../swagger/paths/contacts/{id}/patch.yaml'
  #   delete:
  #     $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    $ref: '../swagger/components/schemas/auth/securitySchemes.yaml'
